</td></tr><tr><td height="20" valign="top">
<br><br><br>
<table width="100%" style="border-width:0" cellpadding="0" cellspacing="0"><tr>
<td align="left">Vers&atilde;o: 0.49BR</td>
<td align="center"><strong>Editado por: <a href="http://www.csonlinebr.net" target="_blank">CS Online</a></strong></td>
<td align="right">Server Aberto  ( {W.uptime} )</td>
</tr></table>
</td></tr></table>
</body>
</html>